### ISSUE TITLE
Keep Alive

### ISSUE THREAD

**Issue by heynemann** [varnish/libvmod-curl#45]
Hi,

Thanks for the awesome vmod. We are trying to use it to call an API in our Paywall solution using Varnish.

We are having trouble because libvmod-curl is not using Keep-Alive. I've tried modifying the vmod to keep connections ESTABLISHED but even when connections keep established, they are not reused.

Are there any plans to implement KeepAlive support in this VMOD?

If not, would you help me implement this?

**Comment by rezan** [comment]
We have written an enhanced version of this vmod called [http](https://docs.varnish-software.com/varnish-cache-plus/vmods/http/). Its subscription only, so not sure if you have access to that.

Otherwise, there are no plans on adding enhancements to vmod-curl. However, this is a community VMOD, so any changes, enhancements, or forks are welcome.
